### ISSUE TITLE
How to send a request from the server to the client?

### ISSUE THREAD

**Issue by heitor-lassarote** [c-cube/linol#16]
I see `notify_back` can send a notification from the server to the client, but I don't see how to do it with a request. In particular, I'm trying to send `ClientRegisterCapability` to accept incoming requests of `ChangeConfiguration`, but I can't see a way to do that without resorting to the low-level API using jsonrpc (and I'm not even sure of this).

Sorry if this is a stupid question, but how can this be achieved with Linol?

**Comment by c-cube** [comment]
I don't think there's an API for that right now :). It could be added to `base_server` in server.ml I suppose. PR welcome if you want!

**Comment by heitor-lassarote** [comment]
I see, thanks for clarifying! I can give a try at implementing this after my vacations end next week. It'll be nice to better familiarize with its internals.

**Comment by heitor-lassarote** [comment]
Just an update: I didn't forget about this issue, only some more important tasks appeared first. I'll begin working on it now.

**Comment by c-cube** [comment]
fyi: there's a branch with a move to lsp 1.14, you should try that. It is more up-to-date wrt the Lsp protocol.

**Comment by heitor-lassarote** [comment]
Thanks for the heads-up, I'll rebase my changes on top of that branch.

**Comment by heitor-lassarote** [comment]
WIP branch rebased on 1.14 branch: https://github.com/serokell/linol/tree/heitor-lassarote/handle-server-requests-lsp-1.14

I hope to have it ready sometime by this week.

**Comment by heitor-lassarote** [comment]
Closing as #18 was merged.
