### ISSUE TITLE
Breaking out a handler for `UnknownRequest`  and `UnknownNotification`

### ISSUE THREAD

**Issue by xldenis** [c-cube/linol#19]
I'm opening an issue first to get your opinion. 

Currently we can write custom handlers for various unknown requests / notifications by special casing `on_unhandled_*`, but this requires writing a GADT signature to the function or getting moderately cryptic errors out from the typechecker. 

Since `UnknownRequest` always has a `Json.t` response we could also provide a separate, simply typed handler which completely masks the underlying GADTness of `Client_request`. 

This doesn't add any new expressiveness but might make the API more friendly to use.

**Comment by c-cube** [comment]
Sorry, I never got around to look at this. That sounds reasonable, a PR would be welcome :)

**Comment by xldenis** [comment]
sounds good, I'll throw one up then.
