### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by SoilihBenSoilih** [c-cube/linol#2]
Hello, 

First of all, thank you for making this library to make things easier to do. 
But how to, actually install it in order to use it? 

Thank you !!!

**Comment by c-cube** [comment]
Hello, it's in very early days so it's not released on opam yet. `opam pin https://github.com/c-cube/linol.git` should do the trick if you use opam.

**Comment by SoilihBenSoilih** [comment]
ooh, ok, thank you !!

**Comment by c-cube** [comment]
the library has been released.
