### ISSUE TITLE
Unicode issue

### ISSUE THREAD

**Issue by wintersteiger** [c-cube/linol#35]
`String.length` here: 
https://github.com/c-cube/linol/blob/0cb01857973aeb443a44991ff0f1407fffef123b/src/jsonrpc2.ml#L99
is sometimes off. 

I'm almost sure that it's because of unicode characters in the string, which take 2 bytes, but print as 1 byte. (The `ε` in `patmatch.ml` trips it every time and it's off by exactly as many `ε` I add.) I think `String.length` actually does return the right number, but whatever printing happens afterwards produces less bytes than expected.

However, according to the OCaml docs, `String.length` returns the "number of bytes/characters", which, I guess, means that it is randomly decided how many bytes correspond to a character...

**Comment by c-cube** [comment]
the wire protocol is jsonrpc, which is based on json (always utf8 afaict). So `String.length` as the number of bytes is correct since this header is always preoccupied with the number of bytes, not codepoints.

However the unicode problem you think of is most likely at the place where we convert positions (since LSP decided to count in UTF16 chars, I think :/)

**Comment by wintersteiger** [comment]
Hmm, I'm not sure it's the positions. Here's an example message:

```
{"params":{"message":"(decompose.loop\n :matrix { Patmatch.Matrix.occs =\n           [(εεεεε, x goal, x goal,\n             in file 'builtin:prelude.iml', line 188 col 17 to line 190 col 28 [6694..6764]\n             188 | ................match x goal with\n             189 |     | Ok x' -> Ok (f x')\n             190 |     | Error err -> Error err\n             )];\n           rows =\n           [{ Patmatch.Matrix.cols = [(Ok((x'/147 : 'a/159)))];\n              subst = {subst: }; des_bs = []; when_ = None;\n              rhs = Ok ((f/136 : 'a/159 -> 'b/160) (x'/147 : 'a/159)) };\n             { Patmatch.Matrix.cols =\n               [(Error\n                 ((err/156 :\n                   (string * Tactic.model option * Tactic.goal list))))\n                 ];\n               subst = {subst: }; des_bs = []; when_ = None;\n               rhs =\n               Error\n               (err/156 : (string * Tactic.model option * Tactic.goal list))\n               }\n             ];\n           cex = None })","type":4},"method":"window/logMessage","jsonrpc":"2.0"}
```

`String.length` says 1081, which is 5 off, and there are 5 `ε`

**Comment by wintersteiger** [comment]
Yep, sorry for the noise, the problem was totally on my end!
