### ISSUE TITLE
Linol release request

### ISSUE THREAD

**Issue by vincent-botbol** [c-cube/linol#43]
Hello,

I would like to publish [my LSP server](https://github.com/CatalaLang/catala-language-server/) on opam but I'm currently stuck as I depend on #42 which has not been released yet.
Is there any plan on releasing a new version soon? If that's complicated I can always vendor `linol` in the meantime so no rush.

Thanks for the hard work

**Comment by c-cube** [comment]
It's done on opam.

**Comment by vincent-botbol** [comment]
Thanks a lot!
