### ISSUE TITLE
Connexion problems

### ISSUE THREAD

**Issue by SoilihBenSoilih** [c-cube/linol#5]
Hello, 

Hope you're going fine !
I'm using Linol in a project to make an lsp-server written in ocaml.
The file i have made is based on the linol template. I have put some static data to
test if it's working before using the real Type checker. I'm using emacs 
as client. the server connect and just right after disconnect with this message
`exited abnormally with code 2`

So I'm here to see if you can help me figure this out.

My code is in the following file : 

[typer_lsp_server.txt](https://github.com/c-cube/linol/files/6271974/typer_lsp_server.txt)

Thank you a lot !!!

**Comment by c-cube** [comment]
With linol 0.2 I had this work pretty well: 

[lsp.txt](https://github.com/c-cube/linol/files/6272560/lsp.txt)
and got this in vim:



![2021-04-07-110011_307x262_scrot](https://user-images.githubusercontent.com/1274291/113888956-cae4a900-9790-11eb-8d88-cee3b2fdf940.png)

**Comment by SoilihBenSoilih** [comment]
Hello, 

It's working after the update for me too.

Thank you very much !!!
